//! Build-script resource embedding: the RockCast icon goes into the Windows
//! .exe so Explorer/taskbar show the brand mark (assets/app-icon.ico,
//! regenerated by scripts/generate_icons.py).

fn main() {
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        println!("cargo:rerun-if-changed=assets/app-icon.ico");
        let mut resource = winresource::WindowsResource::new();
        resource.set_icon("assets/app-icon.ico");
        resource.compile().expect("failed to embed Windows icon resource");
    }
}
